# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-09 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211009_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeofficestuff',
            name='floor',
            field=models.CharField(max_length=20, verbose_name='Floor'),
        ),
    ]
