# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211009_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_code',
            field=models.BooleanField(default=False, verbose_name='Promo code'),
        ),
    ]
