# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='promo_code',
            field=models.BooleanField(default=False, verbose_name='Promo state'),
        ),
        migrations.AddField(
            model_name='book',
            name='service',
            field=models.FloatField(default=0.0, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='book',
            name='storage',
            field=models.FloatField(default=0.0, verbose_name='Storage'),
        ),
    ]
