# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211009_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='promo_code',
            field=models.FloatField(default=0.0, verbose_name='Promo state'),
        ),
    ]
