# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211011_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='promo_code',
            field=models.CharField(default='', max_length=100, verbose_name='Promo code'),
        ),
    ]
