# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211012_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Promo code'),
        ),
    ]
