# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-13 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211013_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeofficestuff',
            name='storage',
        ),
        migrations.AddField(
            model_name='homeofficestuff',
            name='store_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.StoreHouse'),
        ),
    ]
