# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211013_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehouse',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/storehouse/'),
        ),
    ]
