# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211013_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.FileField(upload_to='static/uploads/storage/'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='image',
            field=models.FileField(blank=True, upload_to='static/uploads/storehouse/'),
        ),
    ]
