# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211014_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.FileField(upload_to='static/uploads/storage/'),
        ),
    ]
