# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211014_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.FloatField(default=10, verbose_name='Percent'),
        ),
    ]
