# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_promocode_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='category',
            field=models.CharField(default='', max_length=30, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='colour',
            field=models.CharField(default='', max_length=30, verbose_name='Colour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(default='', max_length=30, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='current_address',
            field=models.CharField(default='', max_length=30, verbose_name='Current address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='currently_drive_for_other',
            field=models.CharField(default='', max_length=30, verbose_name='Currently drive for other'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.CharField(default='', max_length=30, verbose_name='Date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='disability',
            field=models.CharField(default='', max_length=30, verbose_name='Disability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_category',
            field=models.CharField(default='', max_length=30, verbose_name='Driving category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='ethnicity',
            field=models.CharField(default='', max_length=30, verbose_name='Ethnicity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='', max_length=30, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='has_license',
            field=models.CharField(default='', max_length=30, verbose_name='Has license'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='insurance_policy',
            field=models.CharField(default='', max_length=30, verbose_name='Insurance policy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='license_plate_number',
            field=models.CharField(default='', max_length=30, verbose_name='License plate number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='national_insurance_number',
            field=models.CharField(default='', max_length=30, verbose_name='National insurance number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='own_car',
            field=models.CharField(default='', max_length=30, verbose_name='Own car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='post_code',
            field=models.CharField(default='', max_length=30, verbose_name='Post code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='proficiency',
            field=models.CharField(default='', max_length=30, verbose_name='Proficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='seater',
            field=models.CharField(default='', max_length=30, verbose_name='Seater'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='street_name',
            field=models.CharField(default='', max_length=30, verbose_name='Street name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='taxi_license',
            field=models.CharField(default='', max_length=30, verbose_name='Taxi license'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(default='', max_length=30, verbose_name='Vehicle model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(default='', max_length=30, verbose_name='Vehicle type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='year',
            field=models.CharField(default='', max_length=30, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
