# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-15 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211015_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanhire',
            name='store_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books1', to='api.StoreHouse'),
        ),
        migrations.AlterField(
            model_name='vanhire',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vanhire_storage', to='api.Book'),
        ),
    ]
