# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-10-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211015_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanhire',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='van_hire', to='api.Book'),
        ),
    ]
